---
galaxy_info:
  role_name: mailcow
  namespace: hahn-cloud
  author: Lars Hahn
  company: Data Learning
  license: MIT
  description: Role to setup mailcow based on docker.
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - mailcow
dependencies:
  - docker
