---
galaxy_info:
  role_name: easy-rsa
  namespace: hahn-cloud
  author: Lars Hahn
  company: Data Learning
  license: MIT
  description: Role to setup an easy-rsa for PKI, CA and certificates.
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - easy-rsa
dependencies: []