---
galaxy_info:
  role_name: java
  namespace: hahn-cloud
  author: Lars Hahn
  company: OpenDevChain
  license: MIT
  description: Role to setup Java Adoptium / Eclipse Temurin
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - 11
  galaxy_tags:
    - java
dependencies: []
