---
- name: restart gitea
  systemd:
    name: gitea
    state: restarted

- name: generate admin user
  command:
    cmd: |
      {{ gitea_link }}/gitea admin user create
      --admin
      --username {{ gitea_admin_user }}
      --password '{{ gitea_admin_pass }}'
      --email {{ gitea_admin_mail }}
      --config {{ gitea_home }}/app.ini
      --work-path {{ gitea_data_location }}
  become: yes
  become_user: "{{ gitea_usr }}"
