---
galaxy_info:
  role_name: basis
  namespace: hahn-cloud
  author: Lars Hahn
  company: OpenDevChain
  license: MIT
  description: Basis role to setup a basic system with ansible; e.g. Users, Fail2Ban, SSHD
  min_ansible_version: 2.7
  platforms:
    - name: Debian
      versions:
        - 10
  galaxy_tags:
    - basis
dependencies: []
